name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.8
  - pip
  - pytorch=2.0.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - pytorch-cuda=11.8
  - tqdm
  - rtree
  - scikit-learn
  - shapely
  - matplotlib
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
    - opencv-python
